### ISSUE TITLE
[bug] 부트스트랩 적용 실패

### ISSUE THREAD

**Issue by mingxoxo** [peer-42seoul/peer-noti#11]
## 🚅 Issue 한 줄 요약

bootstrap이 적용되지 않는 경우 발생

## 🤷 Issue 세부 내용

bootstrap 깨지는 현상 수정 필요

## 📸 스크린샷

<img width="394" alt="스크린샷 2023-05-31 오전 11 54 30" src="https://github.com/peer-42seoul/peer-noti/assets/43935708/3247342b-9641-4172-9f22-bbdec5385e34">

**Comment by wonyangs** [comment]
확인 결과 Django의 DEBUG 설정을 Ture로 바꾸면 정상적으로 적용이 되었습니다.

DEBUG 설정이 False로 되어 있는 경우, Django는 `runserver` 명령으로 정적 파일을 제공하지 않아 생기는 문제였습니다.

개발 버전에서는 DEBUG 설정을 True로 하여 정적 파일을 간편하게 적용하고, 실제 배포 버전에서는 Apache, nginx 등 웹서버나 AWS와 같은 클라우드에 정적 파일을 올리는 것이 보안상 권장된다고 합니다.

따라서 현재 개발 단계에서는 DEBUG 설정을 True로 하여 bootstrap을 적용시키고, 추후 배포 과정에서 다시 살펴보면 될 것 같습니다!
